"""fix_drift_audit_org_enum_coeff

Revision ID: e49ae646c9ad
Revises: 82f6807130e3
Create Date: 2026-09-15 15:20:51.709381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e49ae646c9ad'
down_revision: Union[str, None] = '82f6807130e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # FK names explicites requis en mode batch SQLite
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_audit_logs_period_id', 'prime_periods', ['period_id'], ['id'])
        batch_op.create_foreign_key('fk_audit_logs_dsm_id', 'dsm', ['dsm_id'], ['id'])

    with op.batch_alter_table('dsm', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dsm_org_id'), ['org_id'], unique=False)

    with op.batch_alter_table('dsm_commissions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('DRAFT', 'CALCULATED', 'ELIGIBLE', 'NON_ELIGIBLE', 'VALIDATED', 'PAID', 'REJECTED', name='statutcommission'),
               existing_nullable=False)

    with op.batch_alter_table('micro_zones', schema=None) as batch_op:
        batch_op.alter_column('potential_coefficient',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('pos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pos_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pos_org_id'))

    with op.batch_alter_table('micro_zones', schema=None) as batch_op:
        batch_op.alter_column('potential_coefficient',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('dsm_commissions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'CALCULATED', 'ELIGIBLE', 'NON_ELIGIBLE', 'VALIDATED', 'PAID', 'REJECTED', name='statutcommission'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('dsm', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dsm_org_id'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_logs_dsm_id', type_='foreignkey')
        batch_op.drop_constraint('fk_audit_logs_period_id', type_='foreignkey')

    # ### end Alembic commands ###
